"""
PDF generation for the FRAME shot list generator.

Converts the raw markdown text returned by the AI into a clean, downloadable
PDF. FPDF renders plain text only, so markdown symbols are stripped with regex
and section headers (## …) are mapped to styled headings.
"""

import re

from fpdf import FPDF

# Characters that fall outside the Latin-1 range supported by FPDF's built-in
# Helvetica font, mapped to safe ASCII equivalents.
_UNICODE_REPLACEMENTS: list[tuple[str, str]] = [
    ("\u2014", "--"),   # em dash
    ("\u2013", "-"),    # en dash
    ("\u2018", "'"),    # left single quotation mark
    ("\u2019", "'"),    # right single quotation mark
    ("\u201c", '"'),    # left double quotation mark
    ("\u201d", '"'),    # right double quotation mark
    ("\u2026", "..."),  # ellipsis
    ("\u00e9", "e"),    # e acute (cafe -> cafe)
    ("\u00e8", "e"),    # e grave
    ("\u00e0", "a"),    # a grave
    ("\u00f6", "o"),    # o umlaut
    ("\u00fc", "u"),    # u umlaut
]


def _sanitize(text: str) -> str:
    """Replace unsupported Unicode characters with Latin-1-safe equivalents."""
    for char, replacement in _UNICODE_REPLACEMENTS:
        text = text.replace(char, replacement)
    # Strip any remaining characters outside Latin-1 to prevent encoding errors
    return text.encode("latin-1", errors="ignore").decode("latin-1")


def generate_pdf(content: str, shoot_type: str) -> bytes:
    """
    Convert an AI-generated markdown shot list into a formatted PDF.

    Args:
        content:    The raw markdown string from the OpenAI response.
        shoot_type: The shoot type label shown in the PDF sub-header.

    Returns:
        The rendered PDF as a bytes object, ready for Streamlit's
        st.download_button or direct file I/O.
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Document header ───────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", size=22)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 12, "FRAME -- Shot List", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(130, 130, 130)
    pdf.cell(
        0, 6,
        f"Type: {shoot_type}   |   Generated by FRAME AI",
        new_x="LMARGIN", new_y="NEXT",
    )

    pdf.ln(4)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # ── Body — parse each line of the AI output ───────────────────────────────
    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            pdf.ln(3)
            continue

        # Guard: if we're close to the page bottom, start a new page before
        # writing a heading block (cell + rule + ln) to avoid the cursor
        # ending up below the printable area before auto-break fires.
        page_bottom = pdf.h - pdf.b_margin
        if stripped.startswith("## "):
            if pdf.get_y() > page_bottom - 25:
                pdf.add_page()
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", size=10)
            pdf.set_text_color(160, 120, 40)   # amber — matches app accent colour
            heading = _sanitize(stripped.replace("## ", "").upper())
            pdf.cell(0, 8, heading, new_x="LMARGIN", new_y="NEXT")
            pdf.set_draw_color(220, 200, 160)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(2)
        else:
            # Body text — strip markdown bold and italic markers, then sanitize
            if pdf.get_y() > page_bottom - 10:
                pdf.add_page()
            pdf.set_font("Helvetica", size=9)
            pdf.set_text_color(50, 50, 50)
            clean = re.sub(r"\*\*(.*?)\*\*", r"\1", stripped)
            clean = re.sub(r"\*(.*?)\*", r"\1", clean)
            clean = _sanitize(clean)
            # new_x="LMARGIN" resets the cursor to the left margin after each
            # cell; fpdf2 2.8+ leaves x at the right edge without this, causing
            # a zero-width error on the next multi_cell call.
            pdf.multi_cell(0, 5.5, clean, new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())
